version: "2"
services:
  fpm:
      build:
        context: ./docker/fpm/
      links:
          - redis
          - mysql
      volumes:
          - .:/var/www/html

  redis:
      image: redis:3
      ports:
        - "6380:6379"
      volumes:
        - redis_data:/var/lib/redis

  mysql:
      image: mysql:5.6
      command: --sql_mode=NO_ENGINE_SUBSTITUTION --character-set-server=utf8 --collation-server=utf8_general_ci -u=root
      ports:
       - "3307:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=dbpass
        - MYSQL_DATABASE=biogram
      volumes:
        - mysql_data:/var/lib/mysql/

  nginx:
        image: nginx:1.9
        ports:
            - "81:80"
        links:
            - fpm
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql_data: {}
  redis_data: {}
